config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    resources :submissions
  end

  resources :jobs
  resources :institutions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "home/index"

  devise_for :users, controllers: { registrations: 'registrations' }
  root "home#index"
end

app/models/administration.rb
class Administration < ApplicationRecord
  belongs_to :user
  belongs_to :institution
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :jobs
  has_many :administrations
  has_many :users, through: :administration
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :institution
  belongs_to :job_type
  has_many   :submissions
end

app/models/job_type.rb
class JobType < ApplicationRecord
  has_many :jobs
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :job
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :administrations
  has_many :institutions, through: :administrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  def index
    @institutions = Institution.all
  end

  def show
  end

  def new
    @institution = Institution.new
  end

  def edit
  end

  def create
    service = Institutions::Creator.new(current_user, institution_params)
    service.call
    @institution = service.record

    if @institution.persisted?
      redirect_to @institution, notice: 'Institution was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_institution
    @institution = Institution.find(params[:id])
  end

  def institution_params
    params.require(:institution).permit(:name, :registration, :email, :phone, :password)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    # TODO REMOVE HARDCODED ATTRIBUTION
    @job.institution = current_user.institutions.take
    @job.job_type = JobType.take

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def update
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def index
    @submissions = Submission.all
  end

  def show
  end

  def new
    @submission = Submission.new
    @jobs       = Job.all
  end

  def edit
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.user = current_user
    @submission.job  = Job.take
    @submission.status = false

    if @submission.save
      redirect_to @submission, notice: 'Submission was successfully created.'
    else
      render :new
    end
  end

  def update
    if @submission.update(submission_params)
      redirect_to @submission, notice: 'Submission was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @submission.destroy
    redirect_to submissions_url, notice: 'Submission was successfully destroyed.'
  end

  private

  def set_submission
    @submission = Submission.find(params[:id])
  end

  def submission_params
    params.require(:submission).permit(:job_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <h2>Hack 2 Save</h2>
  </div>
  <div class="row">
    <div class="col s12 m8 l6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo atque impedit, facilis recusandae culpa laudantium eaque. Minus vitae, debitis aliquam quam cupiditate dolorum est esse sint praesentium natus incidunt eos!</p>
    </div>
    <div class="col s12 m8 l6">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>Pariatur praesentium laboriosam magnam modi natus laudantium quos ad iure.</p>
    </div>
  </div>
</div>


<div class="row">
  <div class="center-align">
    <% if user_signed_in? %>
      <%= link_to "Seja Voluntário", new_submission_path, class:"waves-effect waves-teal btn-flat" %>
      <%= link_to "Cadastre uma Instituição", new_institution_path, class:"waves-effect waves-teal btn-flat" %>
    <% else %>
      <%= link_to "Entrar", new_user_session_path, class:"waves-effect waves-teal btn-flat" %>
      <%= link_to "Cadastrar", new_user_registration_path, class:"waves-effect waves-teal btn-flat" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col s12 m6 l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col s12 m6 l6">
      <h5>#sobrenós Lorem ipsum dolor sit amet, consectetur </h5>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br>
        Dolores deleniti fugit hic sapiente magnam, unde commodi non atque asperiores natus architecto, maxime rem tenetur minus molestias reprehenderit excepturi sequi? Expedita.</p>
      </div>
      <div class="col s12 m6 l6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/institutions/_form.html.erb
<%= simple_form_for @institution do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/institutions/edit.html.erb
<div class="container">
	<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

      
<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>
</div>

app/views/institutions/index.html.erb
<div class="container">
<div class="row">
  <div class="col s12" id="admin">
    <div class="card material-table">
      <div class="table-header">
        <h5>Institutions</h5>
      </div>
      <div id="dttb_wrapper" class="dataTables_wrapper no-footer">
        <table class="table dataTable no-footer dtr-inline" id="dttb"
          role="grid" aria-describedby="dttb_info">
          <thead>
            <tr role="row">
              <th width="30%" class="sorting_asc" tabindex="0"
                aria-controls="dttb" rowspan="1" colspan="1"
                aria-sort="ascending"
                aria-label="Title: activate to sort column descending">Name</th>

              <th width="15%" class="sorting" tabindex="0" aria-controls="dttb" rowspan="1"
                colspan="1" aria-label="Body: activate to sort column ascending">registration</th>

              <th  width="15%"  class="sorting" tabindex="0"
                aria-controls="dttb" rowspan="1" colspan="1"
                aria-label="Published: activate to sort column ascending">email</th>

                <th width="15%"  class="sorting" tabindex="0"
                aria-controls="dttb" rowspan="1" colspan="1"
                aria-label="Published: activate to sort column ascending">phone</th>

              <th  width="15%" class="sorting" tabindex="0" aria-controls="dttb" rowspan="1"
                colspan="1" aria-label=": activate to sort column ascending"></th>
            </tr>
          </thead>
          <tbody>
          <% @institutions.each do |institution| %>
            <tr role="row" class="even">
              <td tabindex="0" class="sorting_1"><%= institution.name %></td>
              <td><%= institution.registration %></td>
              <td><%= institution.email %></td>
              <td><%= institution.phone %></td>
              
            
              <td class="right-align">
              <a> <%= link_to 'Show', institution %> </a>
              <a> <%=link_to 'Edit', edit_institution_path(institution) %> </a>
                <a <%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
       
      </div>
    </div>
  </div>
</div>
</div>

app/views/institutions/new.html.erb
<div class="container">
	<h1>New Institution</h1>

	<%= render 'form', institution: @institution %>

	<%= link_to 'Back', institutions_path %>
</div>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Jobs</h1>

  <%= link_to 'New Job', new_job_path, class: "waves-effect waves-light btn" %>
  <table class="striped">
    <thead>
      <tr>
        <th>Institution</th>
        <th>Job type</th>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.institution.name %></td>
          <td><%= job.job_type.title %></td>
          <td><%= job.title %></td>
          <td><%= link_to 'Show', job %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col s12 m7">
    <h2 class="header"><%= @job.title %></h2>
    <div class="card medium" style="overflow: hidden;">
      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="/images/sample1.jpg">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">
          <%= @job.job_type.title %> - <%= @job.institution.name %>
          <i class="material-icons right">more_vert</i>
        </span>

        <blockquote><%= FFaker::Lorem.phrase %>. <i><%= FFaker::Name.name  %></i></blockquote>
        <blockquote><%= FFaker::Lorem.phrase %>. <i><%= FFaker::Name.name  %></i></blockquote>
      </div>
      <div class="card-reveal" style="display: none; transform: translateY(0px);">
        <span class="card-title grey-text text-darken-4">
          <%= @job.title %><i class="material-icons right">close</i>
        </span>
        <p><%= @job.description %></p>
        <%= link_to "Seja Voluntário", new_submission_path, class:"waves-effect waves-light btn" %>
      </div>
    </div>
  </div>
  <div class="col s12 m5">
    <br><br><br><br>
    <table>
        <thead>
          <tr>
              <th>Shifts Avaliable</th>
              <th>Hours</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Sun</td>
            <td>10am - 15pm</td>
          </tr>
          <tr>
            <td>Mon - Wed</td>
            <td>10am - 15pm</td>
          </tr>
          <tr>
            <td>Fri</td>
            <td>10am - 15pm</td>
          </tr>
        </tbody>
      </table>
    <%= link_to 'Back', jobs_path, class: "waves-effect waves-light btn" %>
  </div>
</div>

<%= link_to 'Edit', edit_job_path(@job) %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l3 s12">
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Home</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <ul>
          <li><%= link_to "Home", root_path, class: "grey-text text-lighten-3" %></li>
          <li><a class="grey-text text-lighten-3" href="#!">Termos & Condições</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Explorar</a></li>
          <li><%= link_to "Cadastrar", new_user_registration_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to "Fazer Login", new_user_session_path, class: "grey-text text-lighten-3" %></li>
          <li><a class="grey-text text-lighten-3" href="#!">Blog</a></li>
        </ul>
      </div>
      <div class="col l6 s12">
        <p class="white-text">Conheça as origens desse projeto</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Copyright IUVO
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navbar -->
<header class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <%= link_to root_path do %>
        <span class="brand-logo">IUVO</span>
      <% end %>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Trabalhos Disponíveis", jobs_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
          <li><%= link_to "Criar uma Instituição", new_institution_path %></li>
          <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="#">Sobre nós</a></li>
          <li><a href="#">Explorar<i class="material-icons left">search</i></a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iuvo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<body>
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>

</html>

app/views/submissions/_form.html.erb
<%= simple_form_for @submission do |f| %>
  <%= f.input :description %>
  <%= f.input :job, collection: @jobs, label_method: :title, value_method: :id, include_blank: false %>
  <%= f.submit %>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Job</th>
      <th>User</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.job %></td>
        <td><%= submission.user %></td>
        <td><%= submission.description %></td>
        <td><%= submission.status %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @submission.job %>
</p>

<p>
  <strong>User:</strong>
  <%= @submission.user %>
</p>

<p>
  <strong>Description:</strong>
  <%= @submission.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @submission.status %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>